mkdir stitch_assets
cd stitch_assets

curl.exe -L "https://contribution.usercontent.google.com/download?c=CgthaWRhX2NvZGVmeBJ8Eh1hcHBfY29tcGFuaW9uX2dlbmVyYXRlZF9maWxlcxpbCiVodG1sXzhlOTgzMWU2MTA5MTQxNjRhY2ViMzdjYTU4MDQ5NmNkEgsSBxDlrPLghwoYAZIBJAoKcHJvamVjdF9pZBIWQhQxMzM3MTc0Nzg4MDc1MjIzNDcyOQ&filename=&opi=89354086" -o login.html

curl.exe -L "https://contribution.usercontent.google.com/download?c=CgthaWRhX2NvZGVmeBJ8Eh1hcHBfY29tcGFuaW9uX2dlbmVyYXRlZF9maWxlcxpbCiVodG1sXzcwMGVlZGMwNTEzNzQ4YjFiZmI3NTRiOTZiY2IxMjgyEgsSBxDlrPLghwoYAZIBJAoKcHJvamVjdF9pZBIWQhQxMzM3MTc0Nzg4MDc1MjIzNDcyOQ&filename=&opi=89354086" -o member_management.html

curl.exe -L "https://contribution.usercontent.google.com/download?c=CgthaWRhX2NvZGVmeBJ8Eh1hcHBfY29tcGFuaW9uX2dlbmVyYXRlZF9maWxlcxpbCiVodG1sX2U2Yjk2YTc5MWE4ZTQ5ZmI4ZDk5MzhhN2U1ZDRiN2VlEgsSBxDlrPLghwoYAZIBJAoKcHJvamVjdF9pZBIWQhQxMzM3MTc0Nzg4MDc1MjIzNDcyOQ&filename=&opi=89354086" -o member_dashboard.html

curl.exe -L "https://contribution.usercontent.google.com/download?c=CgthaWRhX2NvZGVmeBJ8Eh1hcHBfY29tcGFuaW9uX2dlbmVyYXRlZF9maWxlcxpbCiVodG1sXzY5MTc5NGJkZGEyYzQzMTY5M2E5ZTg1NjJmMzc5NTAxEgsSBxDlrPLghwoYAZIBJAoKcHJvamVjdF9pZBIWQhQxMzM3MTc0Nzg4MDc1MjIzNDcyOQ&filename=&opi=89354086" -o scheduling.html

curl.exe -L "https://contribution.usercontent.google.com/download?c=CgthaWRhX2NvZGVmeBJ8Eh1hcHBfY29tcGFuaW9uX2dlbmVyYXRlZF9maWxlcxpbCiVodG1sXzQwNzAxMjk1MTRlNTQ1Yjc5ZGVlNzI2ODFhZWQyODAwEgsSBxDlrPLghwoYAZIBJAoKcHJvamVjdF9pZBIWQhQxMzM3MTc0Nzg4MDc1MjIzNDcyOQ&filename=&opi=89354086" -o trainer_directory.html

curl.exe -L "https://contribution.usercontent.google.com/download?c=CgthaWRhX2NvZGVmeBJ8Eh1hcHBfY29tcGFuaW9uX2dlbmVyYXRlZF9maWxlcxpbCiVodG1sX2MxMTFiNDdiYTIzMTQ5N2Y4NWY1MTgyYzFkNmE5MTg3EgsSBxDlrPLghwoYAZIBJAoKcHJvamVjdF9pZBIWQhQxMzM3MTc0Nzg4MDc1MjIzNDcyOQ&filename=&opi=89354086" -o session_management.html

curl.exe -L "https://contribution.usercontent.google.com/download?c=CgthaWRhX2NvZGVmeBJ8Eh1hcHBfY29tcGFuaW9uX2dlbmVyYXRlZF9maWxlcxpbCiVodG1sXzAzZmZlZGJkZTRmNjQ4OTY5MGU2YzE0YjZkYmExYTMzEgsSBxDlrPLghwoYAZIBJAoKcHJvamVjdF9pZBIWQhQxMzM3MTc0Nzg4MDc1MjIzNDcyOQ&filename=&opi=89354086" -o subscription_management.html

curl.exe -L "https://contribution.usercontent.google.com/download?c=CgthaWRhX2NvZGVmeBJ8Eh1hcHBfY29tcGFuaW9uX2dlbmVyYXRlZF9maWxlcxpbCiVodG1sXzAwZGEwZjljNGQ2NzQ4YmM5MjQ1OTgyMzM3ZmQxNjYyEgsSBxDlrPLghwoYAZIBJAoKcHJvamVjdF9pZBIWQhQxMzM3MTc0Nzg4MDc1MjIzNDcyOQ&filename=&opi=89354086" -o system_settings.html
